#!/usr/bin/env bash


# Herbstluftwm start
hc() {
    herbstclient "$@"
}



hc emit_hook reload


# KEYBINDINGS

# remove all existing keybindings
hc keyunbind --all

# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1  # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# hc keybind $Mod-Shift-x quit
# hc keybind $Mod-F2 reload
# hc keybind $Mod-Shift-q close
# hc keybind $Mod-q close

#Most of the keybindings have been set in sxhkd config file
#you can set them also here

#reload sxhkd - see keybind in sxhkd
#hc keybind $Mod-Shift-s  pkill -USR1 -x sxhkd

# MOVEMENTS

# focusing clients
#hc keybind $Mod-Left  focus left
#hc keybind $Mod-Down  focus down
#hc keybind $Mod-Up    focus up
#hc keybind $Mod-Right focus right
#hc keybind $Mod-h     focus left
#hc keybind $Mod-j     focus down
#hc keybind $Mod-k     focus up
#hc keybind $Mod-l     focus right

# moving clients to ... on single Monitor
#hc keybind $Mod-Shift-Left  shift left
#hc keybind $Mod-Shift-Down  shift down
#hc keybind $Mod-Shift-Up    shift up
#hc keybind $Mod-Shift-Right shift right
#hc keybind $Mod-Shift-h     shift left
#hc keybind $Mod-Shift-j     shift down
#hc keybind $Mod-Shift-k     shift up
#L hc keybind $Mod-Shift-l     shift right

# moving clients to ... on dual monitor
# hc keybind $Mod-Shift-h chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# hc keybind $Mod-Shift-Left chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# hc keybind $Mod-Shift-j chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# hc keybind $Mod-Shift-Down chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# hc keybind $Mod-Shift-k chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
# hc keybind $Mod-Shift-Up chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
# hc keybind $Mod-Shift-l chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
# hc keybind $Mod-Shift-Right chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# FRAMES

# create an empty frame at the specified direction
#hc keybind $Mod-u       split   bottom  0.5
#hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
#hc keybind $Mod-Control-space split explode
# remove frame
hc keybind $Mod-Control-m remove

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# TAGS or WORKSPACES

#names to display in menu
#tag_names=( {1..10} )
tag_names=("Web" "Chat" "Edit" "Misc" "Virtual" "Media" "Steam" "Work" "Music")
#tag_names=( "" "" "" "" "" "" "" "" "" )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting
#hc keybind $Mod-s floating toggle
#hc keybind $Mod-f fullscreen toggle
#hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus on ...
#hc keybind $Mod-BackSpace   cycle_monitor
#hc keybind $Mod-Tab         use_index +1 --skip-visible
#hc keybind $Mod-Shift-Tab   use_index -1 --skip-visible
#hc keybind Control-Mod1-Left    focus left
#hc keybind Control-Mod1-Up      focus up
#hc keybind Control-Mod1-Right   focus right
#hc keybind Control-Mod1-Down    focus down
#hc keybind Mod1-Tab         use_index +1 --skip-visible
#hc keybind Mod1-Shift-Tab   use_index -1 --skip-visible
#hc keybind $Mod-c cycle
# hc keybind $Mod1-i jumpto urigent

#reset prior to setting the theme
#hc attr theme.reset 1

# Attribute
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.active.color '#c63737'
hc attr theme.active.inner_color '#141414'
hc attr theme.active.outer_color '#6790EB'
hc attr theme.background_color '#141414'
#hc attr theme.border_width 3
hc attr theme.normal.border_width 0
hc attr theme.active.border_width 3
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.inner_color black
hc attr theme.inner_width 0
hc attr theme.outer_witdh 0
hc attr theme.normal.color '#141414'
hc attr theme.urgent.color orange

# Set

hc set always_show_frame 0
hc set focus_follows_mouse 1
hc set frame_border_active_color '#c63737'
hc set frame_border_normal_color '#141414'
hc set frame_bg_normal_color '#141414'
hc set frame_bg_active_color '#0A3639'
#hc set frame_bg_active_color 'transparent'
hc set frame_border_width 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0
hc set frame_padding 0
hc set mouse_recenter_gap 0
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 0
#hc set tree_style '╾│ ├└╼─┐'
hc set_layout horizontal
#herbstclient set_layout grid

hc set window_gap 15


hc load Media '
(split horizontal:0.450000:1
 (clients vertical:0 0x2400001)
 (split vertical:0.300000:1
 (split horizontal:0.500000:0
 (clients vertical:0 0x1c01116)
 (clients vertical:0 0x1c013bd))
 (clients vertical:0 0x1c010da)))
'



# RULES
hc unrule -F
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients

#assign applications to workspaces or tags
hc rule class~'(brave|Brave-browser|Chromium|Google-chrome)' tag='Web' switchtag=on focus=on
hc rule class='Spotify' tag='Music' switchtag=on focus=on
hc rule class='Subl3' tag='Edit'  switchtag=on focus=on
hc rule class~'(discord|Discord)' tag='Chat' switchtag=on focus=on
hc rule class~'(vlc|mpv|Mpv)' tag='Media' switchtag=on focus=on
hc rule class~'(VirtualBox Manager|Vmplayer)' tag='Virtual' switchtag=on focus=on
hc rule class~'(Thunar|Pcmanfm|Nemo)' tag='Work' switchtag=on focus=on
hc rule class~'(Shotcut|Gpick|gpick)' floating=on
hc rule class~'(gimp|Gimp)' tag='Misc' switchtag=on focus=on

# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hhc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=VirtualBox fullscreen=on

# unlock, just to be sure
hc unlock

hc set set tree_style '?| ++?-+'

#Dualmonitor setup
# Find out your monitor name with xrandr or arandr (save and you get this line)
#xrandr --output VGA-1 --primary --mode 1360x768 --pos 0x0 --rotate normal
#xrandr --output DP2 --primary --mode 1920x1080 --rate 60.00 --output LVDS1 --off &
#xrandr --output LVDS1 --mode 1366x768 --output DP3 --mode 1920x1080 --right-of LVDS1
#xrandr --output HDMI2 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off


#Dualmonitor setup
# hc detect_monitors
#hc set_monitors 1920x1080+0+0 1920x1080+1920+0
#hc remove_monitor 1


#room for polybar on both monitors
# find the panel
panel=~/.config/polybar/launch.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
start it on each monitor
"$panel" $monitor &
#hc pad 0 "" "" 25
hc pad 0 23
#hc pad 0 "" 5
#hc pad 0 "" "" "" 5
done



